app1/urls.py
from django.urls import include, path
from django.views.generic import RedirectView
from app1.views import BookingCreateView, BookingUpdateView, App1BookingConfirmationView

app_name = 'app1'

urlpatterns = [
    path('create/', BookingCreateView.as_view(), name='app1_create'),
    path('update/', BookingUpdateView.as_view(), name='app1_update'),
    path('confirm/', App1BookingConfirmationView.as_view(), name='confirm'),
]

client_panel/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView, LogoutView
from django.urls import path, include, reverse_lazy
from client_panel.views import BookingCreateView, SignUpCreateView, Login, CPBookingConfirmationView

booking_patterns = ([
                        path('create/', BookingCreateView.as_view(), name='create'),
                        path('confirm/', CPBookingConfirmationView.as_view(), name='confirm'),
                    ], 'booking')


registration_patterns = ([
                             path('login/', Login.as_view(), name='login'),
                             path('logout/', LogoutView.as_view(), name='logout'),
                             path('password_reset/', PasswordResetView.as_view(
                                 success_url=reverse_lazy('registration:password_reset_done')), name='password_reset'),
                             path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
                             path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                                 success_url=reverse_lazy('registration:password_reset_complete')),
                                  name='password_reset_confirm'),
                             path('password_reset_complete/', PasswordResetCompleteView.as_view(),
                                  name='password_reset_complete'),
                             path('sign_up/', SignUpCreateView.as_view(success_url=reverse_lazy('registration:login')),
                                  name='sign_up')
                         ], 'registration')

urlpatterns = [
    path('booking/', include(booking_patterns, namespace='booking')),
    path('registration/', include(registration_patterns, namespace='registration')),
]

main_page/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

import app2
from app1.views import App1BookingConfirmationView
from app2.views import App2BookingConfirmationView
from client_panel.views import CPBookingConfirmationView
from main_page import tasks
from main_page.views import MainPageView, BookingListView, ChooseDateView, BookingDetailView, AboutUsView, ContactView, \
    FAQView, RouteView, KayaksView, PriceListView, HowItLooksView, ProfileView, DeleteUserView, \
    DeleteUserConfirmationView, PrivacyPolicyView, AdminPanelView, BookingSuccessfulConfirmationView, \
    BookingPlaceHolderView, BookingDeleteView

app_name = 'main'

urlpatterns = [
    path('', MainPageView.as_view(), name='main'),
    path('booking_confirmation/', BookingDetailView.as_view(), name='booking_detail'),
    path('my_booking/', BookingListView.as_view(), name='my_booking'),
    path('choose_date', ChooseDateView.as_view(), name='choose_date'),
    path('about_us', AboutUsView.as_view(), name='about_us'),
    path('FAQ', FAQView.as_view(), name='faq'),
    path('contact', ContactView.as_view(), name='contact'),
    path('route', RouteView.as_view(), name='route'),
    path('kayaks', KayaksView.as_view(), name='kayaks'),
    path('price_list', PriceListView.as_view(), name='price_list'),
    path('how', HowItLooksView.as_view(), name='how'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('user_delete', DeleteUserView.as_view(), name='user_delete'),
    path('user_delete_confirmation', DeleteUserConfirmationView.as_view(), name='user_delete_confirmation'),
    path('privacy_policy', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('qzxwce1928', AdminPanelView.as_view(), name='admin_panel'),
    path('thanks', BookingSuccessfulConfirmationView.as_view(), name='thanks'),
    path('confirm', BookingPlaceHolderView.as_view(), name='confirm'),
    path('delete_booking', BookingDeleteView.as_view(), name='delete_booking'),
    path('app1/', RedirectView.as_view(pattern_name='app1:app1_create')),
    path('client_panel/', RedirectView.as_view(pattern_name='booking:create')),
    path('app2/', RedirectView.as_view(pattern_name='app2:app2_create')),
    path('change_status/<int:pk>/', tasks.change_status, name='change_status'),
    path('booking_delete/<int:pk>/', tasks.booking_delete, name='booking_delete')
]

wanplac_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from wanplac_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('client_panel/', include('client_panel.urls')),
    path('app1/', include('app1.urls', namespace='app1')),
    path('app2/', include('app2.urls', namespace='app2')),
    path('main/', include('main_page.urls', namespace='main'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
import datetime
from typing import Dict, Any

from celery.contrib import rdb
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils import formats
from django.views.generic import TemplateView, ListView, DeleteView, UpdateView
import app1
import app2
import client_panel
from client_panel.models import DateList
from app2.models import DateList
from app1.models import DateList


class MainPageView(TemplateView):
    template_name = 'main_page/main.html'


class AboutUsView(TemplateView):
    template_name = 'main_page/about_us.html'


class FAQView(TemplateView):
    template_name = 'main_page/FAQ.html'

    def get_context_data(self, **kwargs):
        context = super(FAQView, self).get_context_data()
        context['faq'] = client_panel.models.FAQ.objects.all().order_by('id')
        return context


class ContactView(TemplateView):
    template_name = 'main_page/contact.html'


class RouteView(TemplateView):
    template_name = 'main_page/route.html'

    def get_context_data(self, **kwargs):
        context = super(RouteView, self).get_context_data()
        context['route'] = client_panel.models.Route.objects.all()
        return context


class KayaksView(TemplateView):
    template_name = 'main_page/kayaks.html'

    def get_context_data(self, **kwargs):
        context = super(KayaksView, self).get_context_data()
        context['kayak'] = client_panel.models.Kayak.objects.all().order_by('type')
        return context


class PriceListView(TemplateView):
    template_name = 'main_page/price_list.html'

    def get_context_data(self, **kwargs):
        context = super(PriceListView, self).get_context_data()
        context['kayak'] = client_panel.models.Kayak.objects.all().order_by('type')
        context['route'] = client_panel.models.Route.objects.all()
        return context


class HowItLooksView(TemplateView):
    template_name = 'main_page/how.html'


class ProfileView(TemplateView):
    template_name = 'main_page/profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data()
        context['user'] = User.objects.get(username=self.request.user)
        return context


class ChooseDateView(LoginRequiredMixin, TemplateView):
    template_name = 'main_page/choose_date.html'

    def get_context_data(self, **kwargs):
        context = super(ChooseDateView, self).get_context_data(**kwargs)
        if self.request:
            context['current_day'] = datetime.datetime.now().date()
            context['next_day'] = datetime.datetime.now().date() + datetime.timedelta(days=1)
            context['next_next_day'] = datetime.datetime.now().date() + datetime.timedelta(days=2)
            context['next_next_next_day'] = datetime.datetime.now().date() + datetime.timedelta(days=3)
            context['client_panel_date_list'] = client_panel.models.DateList.objects.values_list('date', flat=True)
            context['app2_date_list'] = app2.models.DateList.objects.values_list('date', flat=True)
            context['app1_date_list'] = app1.models.DateList.objects.values_list('date', flat=True)
            context['current_time'] = datetime.datetime.now().time()
            context['start_break'] = datetime.time(11, 45)
            context['stop_break'] = datetime.time(12, 15)
            return context


class BookingListView(LoginRequiredMixin, ListView):
    template_name = 'main_page/my_booking.html'
    queryset = app1.models.Booking.objects.all()

    def get_context_data(self, **kwargs):
        # rdb.set_trace()
        context = super(BookingListView, self).get_context_data()
        my_booking_app1 = app1.models.Booking.objects.filter(user=self.request.user)
        my_kayak_app1 = app1.models.TermKayaks.objects.filter(booking__user=self.request.user)
        my_booking_app2 = app2.models.Booking.objects.filter(user=self.request.user)
        my_kayak_app2 = app2.models.TermKayaks.objects.filter(booking__user=self.request.user)
        my_booking_client_panel = client_panel.models.Booking.objects.filter(user=self.request.user)
        my_kayak_client_panel = client_panel.models.TermKayaks.objects.filter(booking__user=self.request.user)
        my_date_app1 = app1.models.BookingDate.objects.all()
        my_date_app2 = app2.models.BookingDate.objects.all()
        my_date_client_panel = client_panel.models.BookingDate.objects.all()
        union = my_booking_app1.union(my_booking_app2, my_booking_client_panel).order_by('-exact_time')
        context['union'] = union
        context['union_content'] = len(union)
        context['kayak'] = my_kayak_app2.union(my_kayak_app1, my_kayak_client_panel).distinct('booking_id')
        context['date'] = my_date_app1.union(my_date_app2, my_date_client_panel)
        context['current_day'] = datetime.datetime.now().date()
        context['app1_date'] = my_date_app1.last()
        context['app2_date'] = my_date_app2.last()
        context['cp_date'] = my_date_client_panel.last()
        context['current_time'] = datetime.datetime.now().time()
        context['max_booking_confirm_time'] = datetime.time(9, 30)
        context['last_date_list'] = [my_date_app1.last(), my_date_app2.last(), my_date_client_panel.last()]
        return context


class BookingDetailView(LoginRequiredMixin, ListView):
    template_name = 'main_page/booking_detail.html'
    queryset = app1.models.Booking.objects.all()

    def get_context_data(self, **kwargs):
        data = super(BookingDetailView, self).get_context_data()
        my_booking_app1 = app1.models.Booking.objects.filter(user=self.request.user)
        my_kayak_app1 = app1.models.TermKayaks.objects.filter(booking__user=self.request.user)
        my_booking_app2 = app2.models.Booking.objects.filter(user=self.request.user)
        my_kayak_app2 = app2.models.TermKayaks.objects.filter(booking__user=self.request.user)
        my_booking_client_panel = client_panel.models.Booking.objects.filter(user=self.request.user)
        my_kayak_client_panel = client_panel.models.TermKayaks.objects.filter(booking__user=self.request.user)
        union = my_booking_app1.union(my_booking_app2, my_booking_client_panel).latest('exact_time')
        my_date_app1 = app1.models.BookingDate.objects.all()
        my_date_app2 = app2.models.BookingDate.objects.all()
        my_date_client_panel = client_panel.models.BookingDate.objects.all()
        data['union'] = union
        data['kayak'] = my_kayak_app2.union(my_kayak_app1, my_kayak_client_panel).distinct('booking_id')
        data['date'] = my_date_app1.union(my_date_app2, my_date_client_panel)
        data['current_day'] = datetime.datetime.now().date()
        data['app1_date'] = my_date_app1.latest('id')
        data['app2_date'] = my_date_app2.latest('id')
        data['cp_date'] = my_date_client_panel.latest('id')
        return data


class DeleteUserView(DeleteView):
    template_name = 'main_page/user_delete.html'
    success_url = reverse_lazy('main:user_delete_confirmation')

    def get_object(self, queryset=None):
        user_ = self.request.user
        return get_object_or_404(User, username=user_)

    def get_context_data(self, **kwargs):
        context = super(DeleteUserView, self).get_context_data()
        context['user'] = User.objects.get(username=self.request.user)
        return context


class DeleteUserConfirmationView(TemplateView):
    template_name = 'main_page/user_delete_confirmation.html'


class PrivacyPolicyView(TemplateView):
    template_name = 'main_page/privacy_policy.html'

    def get_context_data(self, **kwargs):
        context = super(PrivacyPolicyView, self).get_context_data()
        context['privacy_policy'] = client_panel.models.PrivacyPolicy.objects.all().order_by('id')
        return context


class AdminPanelView(LoginRequiredMixin, TemplateView):
    template_name = 'main_page/admin_panel.html'

    # queryset = app1.models.Booking.objects.all()

    def get_context_data(self, **kwargs):
        context = super(AdminPanelView, self).get_context_data()
        my_booking_app1 = app1.models.Booking.objects.all()
        my_kayak_app1 = app1.models.TermKayaks.objects.all()
        my_booking_app2 = app2.models.Booking.objects.all()
        my_kayak_app2 = app2.models.TermKayaks.objects.all()
        my_booking_client_panel = client_panel.models.Booking.objects.all()
        my_kayak_client_panel = client_panel.models.TermKayaks.objects.all()
        my_date_app1 = app1.models.BookingDate.objects.all()
        my_date_app2 = app2.models.BookingDate.objects.all()
        my_date_client_panel = client_panel.models.BookingDate.objects.all()
        union = my_booking_app1.union(my_booking_app2, my_booking_client_panel)
        context['union'] = union.order_by('-exact_time')
        context['kayak'] = my_kayak_app2.union(my_kayak_app1, my_kayak_client_panel).distinct('booking_id')
        context['date'] = my_date_app1.union(my_date_app2, my_date_client_panel).order_by('-booking_date')
        context['app1_current_day'] = app1.models.BookingDate.objects.latest('booking_date')
        context['app1_current_kayak'] = app1.models.Kayak.objects.all().order_by('id')
        context['app2_current_day'] = app2.models.BookingDate.objects.latest('booking_date')
        context['app2_current_kayak'] = app2.models.Kayak.objects.all().order_by('id')
        context['client_panel_current_day'] = client_panel.models.BookingDate.objects.latest('booking_date')
        context['client_panel_current_kayak'] = client_panel.models.Kayak.objects.all().order_by('id')
        context['change_booking_state'] = datetime.time(9)
        context['current_time'] = datetime.datetime.now().time()
        context['current_day'] = datetime.datetime.now().date()
        return context

templates/main_page/booking_delete.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %} Dziękujemy za potwierdzenie {% endblock %}
{% block body %}

{% include "main_page/navbar.html" %}

<div class="limiter">
    <div class="container-login100 flex-sb flex-w m-b-120" style="min-height: auto">
        <div class="row login100-form" style="width:600px">
            {% csrf_token %}

            {% if user.is_superuser %}
                <div style="width: 100%">
                    <a class="quick-btn" href="{% url 'main:admin_panel' %}" style="width: 100%; font-size: 20px">
                        Powrót do panelu admina</a>
                </div>
                <span class="login100-form-title p-b-51 m-t-100" style="min-height: 50vh">
                    Rezerwacja została usunięta
                </span>
            {% else %}
                <div style="width: 100%">
                    <a class="quick-btn" href="{% url 'main:my_booking' %}" style="width: 100%; font-size: 20px">
                        Powrót do Moje Zamówienia</a>
                </div>
                <span class="login100-form-title p-b-51 m-t-100" style="min-height: 50vh">
                    Rezerwacja została usunięta
                </span>
            {% endif %}
        </div>
    </div>
</div>

{% include "main_page/footerbar.html" %}

{% endblock %}

{% block body_scripts_additional %}



{% endblock body_scripts_additional %}

templates/main_page/main.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %} Strona główna {% endblock %}
{% block body %}

{% include "main_page/navbar.html" %}


<div class="container-login100 flex-sb flex-w m-b-120" style="min-height: auto; padding: 5px;">
    <div class="row login100-form" style="width:600px">
        {% csrf_token %}
        <div class="m-b-40 m-t-40" style="font-size: 20px; font-family: Ubuntu-Bold; text-align: center">
            Witamy w aplikacji do rezerawcji kajków firmy WAN-PLAC KRUTYŃ.
        </div>
        <div class="m-b-20" style="text-align: justify; font-family: Ubuntu-Bold">
            Nasza aplikacja pozwoli Ci w prosty sposób na rezerawcję kajków w kilku krokach. Zanim przejdziesz do realizacji swojego zamówienia zapoznaj się z Menu w prawym górnym rogu.
        </div>

        {% if user.is_authenticated %}
            <div class="m-t-50">
                <a type="button" class="btn main-page-button button1" href="{% url 'main:route' %}">
                    <span class="m-t-50">1. Nasze TRASY</span></a>
            </div>

            <div>
                <a type="button" class="btn main-page-button button2" href="{% url 'main:kayaks' %}">
                    <span class="m-t-50">2. Zobacz KAJAKI</span></a>
            </div>
            <div>
                <a type="button" class="main-page-button button4" href="{% url 'main:choose_date' %}">
                    <span class="m-t-50">3. Zarezewuj KAJAKI</span></a>
            </div>
        {% else %}
            <div class="m-t-50">
                <a type="button" class="btn main-page-button button1" href="{% url 'main:route' %}">
                    <span class="m-t-50">1. Nasze TRASY</span></a>
            </div>

            <div>
                <a type="button" class="btn main-page-button button2" href="{% url 'main:kayaks' %}">
                    <span class="m-t-50">2. Zobacz KAJAKI</span></a>
            </div>

            <div  class="m-t-40 m-b-10 main-price-list" style="width: 100%; text-align: center">
                <i class="fas fa-arrow-down" style="color: #fb8c00"></i>
                Aby zarezerwować kajaki
                <i class="fas fa-arrow-down" style="color: #fb8c00"></i>
            </div>

            <div>
                <a type="button" class="btn main-page-button button3" href="{% url 'registration:sign_up' %}">
                    <span class="m-t-50">3. Załóż KONTO</span>
                    </a>
            </div>

        {% endif %}

        <div  class="m-b-40 m-t-40 main-price-list">
            Zobacz CENNIK <i class="fas fa-long-arrow-alt-right m-l-10" style="color: #fb8c00"></i>
            <a href="{% url 'main:price_list' %}" class="m-l-10 m-b-10" style="font-family: Ubuntu-Bold; font-size: 25px; color: #827ffe" onmouseover="this.style.color='black'" onmouseout="this.style.color='#827ffe'">
            więcej</a>
        </div>
        <div  class="m-b-40 main-price-list">
            Tak to WYGLĄDA<i class="fas fa-long-arrow-alt-right m-l-10" style="color: #fb8c00"></i>
            <a href="{% url 'main:how' %}" class="m-l-10 m-b-10" style="font-family: Ubuntu-Bold; font-size: 25px; color: #827ffe" onmouseover="this.style.color='black'" onmouseout="this.style.color='#827ffe'">
            więcej</a>
        </div>
        <div  class="m-b-40 main-price-list">
            Kontakt<i class="fas fa-long-arrow-alt-right m-l-10" style="color: #fb8c00"></i>
            <a href="{% url 'main:contact' %}" class="m-l-10 m-b-10" style="font-family: Ubuntu-Bold; font-size: 25px; color: #827ffe" onmouseover="this.style.color='black'" onmouseout="this.style.color='#827ffe'">
            więcej</a>
        </div>
        <div  class="main-price-list" style="font-size: 25px">
            Odwiedź naszą stronę<i class="fas fa-long-arrow-alt-right m-l-10" style="color: #fb8c00; font-size:25px"></i>
            <a target="_blank" href="https://krutyniasplywy.pl/" class="m-l-10 m-b-10" style="font-family: Ubuntu-Bold; font-size: 25px; color: #827ffe" onmouseover="this.style.color='black'" onmouseout="this.style.color='#827ffe'">
            krutyniasplywy.pl</a>
        </div>


    </div>
</div>

{% include "main_page/footerbar.html" %}

{% endblock %}

{% block body_scripts_additional %}



{% endblock body_scripts_additional %}

templates/main_page/navbar.html
{% load static %}

<div class="header clearfix">

    <nav class="navbar navbar-expand-lg static-top" style="background-color: #fff">
        <div class="row" style="width:100%">
            <div class="col-sm-2">
                <a href="{% url 'main:main' %}"><img id="logo" src="{% static 'media/logo.jpg' %}"  width="120" height="86"></a>
            </div>
            <div class="col-sm-8 p-t-10">
                <p class="login100-form-title">Wan-Plac Krutyń</p>
                <div>
                    <p class="login100" style="font-family: Ubuntu-Bold; color: #403866; text-align:center">Aplikacja do rezerwacji kajaków online</p>
                </div>
            </div>
        </div>
    </nav>

    <nav class="navbar navbar-expand-lg static-top" style="background-color: #fb8c00">
        <div class="container">
            <div>
                <a class="nav-item" href="{% url 'main:main' %}" style="text-align:left; color: #fff" onmouseover="this.style.color='black'" onmouseout="this.style.color='#fff'">
                    Strona główna</a>
            </div>
            <div id="navbarResponsive">
                <ul class="navbar">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <button class="nav-link dropdown" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style=" color: #fff; font-size: 20px" onmouseover="this.style.color='black'" onmouseout="this.style.color='#fff'">
                                Menu <i class="fas fa-bars"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="right: 0; left: auto;">
                                <a class="dropdown-item" href="{% url 'main:contact' %}" style=" color: #black;">Kontakt</a>
                                <a class="dropdown-item" href="{% url 'main:price_list' %}" style=" color: #black;">Cennik</a>
                                <a class="dropdown-item" href="{% url 'main:how' %}" style=" color: #black;">Tak to wygląda</a>
                                <a class="dropdown-item" href="{% url 'main:about_us' %}" style=" color: #black;">O nas</a>
                                <a class="dropdown-item" href="{% url 'main:faq' %}" style=" color: #black;">Pytania i odpowiedzi</a>
                                <a class="dropdown-item" href="{% url 'main:my_booking' %}" style=" color: #black;">Moje zamówienia</a>
                                <a class="dropdown-item" href="{% url 'main:profile' %}" style=" color: #black;">Moje konto</a>
                                <a class="dropdown-item" href="{% url 'main:privacy_policy' %}" style=" color: #black;">Polityka prywatności</a>
                                <a class="dropdown-item" href="{% url 'registration:logout' %}" style=" color: #black;">Wyloguj się</a>
                                {% if user.is_superuser %}
                                    <a class="dropdown-item" href="{% url 'main:admin_panel' %}" style=" color: red;"><b>ADMIN</b></a>
                                {% endif %}
                            </div>
                        </li>
                    {% else %}
                         <li class="nav-item dropdown">
                            <button class="nav-link dropdown" id="navbarDropdownNoLogin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style=" color: #fff; font-size: 20px" onmouseover="this.style.color='black'" onmouseout="this.style.color='#fff'">
                                Menu <i class="fas fa-bars"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownNoLogin" style="right: 0; left: auto;">
                                <a class="dropdown-item" href="{% url 'main:contact' %}" style=" color: #black;">Kontakt</a>
                                <a class="dropdown-item" href="{% url 'main:price_list' %}" style=" color: #black;">Cennik</a>
                                <a class="dropdown-item" href="{% url 'main:how' %}" style=" color: #black;">Tak to wygląda</a>
                                <a class="dropdown-item" href="{% url 'main:about_us' %}" style=" color: #black;">O nas</a>
                                <a class="dropdown-item" href="{% url 'main:faq' %}" style=" color: #black;">Pytania i odpowiedzi</a>
                                <a class="dropdown-item" href="{% url 'main:privacy_policy' %}" style=" color: #black;">Polityka prywatności</a>
                                <a class="dropdown-item" href="{% url 'registration:login' %}" style=" color: #black;">Zaloguj się</a>
                                <a class="dropdown-item" href="{% url 'registration:sign_up' %}" style=" color: #black;">Załóż konto</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <nav>
        <div class="row">
            {% if user.is_authenticated %}
                <ul class="col-sm-6">
                     <li class="login100 p-t-10 m-l-20" style="font-family: Ubuntu-Bold; color: #403866; text-align:left; font-size:20px">Witaj {{ user.first_name }}</li>
                </ul>
            {% endif %}
        </div>


    </nav>
</div>

templates/main_page/profile.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %} Moje konto {% endblock %}
{% block body %}

{% include "main_page/navbar.html" %}


<div class="container-login100 flex-sb flex-w m-b-120" style="min-height: auto; align-items: start">
    <div class="row login100-form" style="width:600px">
        {% csrf_token %}

        <div class="m-t-50">
            <div class="main-price-list m-b-40" style="width: 600px; padding: 0px; text-align: center;">
                Moje dane
            </div>

            <div class="m-b-50 m-t-20">
                <div class="row" style="height: 35px">
                    <div class="col-sm-6 profile-subtitle">
                        Nazwa użytkownika:
                    </div>
                    <div class="col-sm-6 profile-variable">
                        {{ user.username }}
                    </div>
                </div>
                <div class="row" style="height: 35px">
                    <div class="col-sm-6 profile-subtitle">
                        Imię i nazwisko:
                    </div>
                    <div class="col-sm-6 profile-variable">
                        {{ user.first_name }} {{ user.last_name }}
                    </div>
                </div>
                <div class="row" style="height: 35px">
                    <div class="col-sm-6 profile-subtitle">
                        Adres email:
                    </div>
                    <div class="col-sm-6 profile-variable">
                        {{ user.email }}
                    </div>
                </div>
                <div class="row" style="height: 35px">
                    <div class="col-sm-6 profile-subtitle">
                        Data dołączenia:
                    </div>
                    <div class="col-sm-6 profile-variable">
                        {% language 'pl' %}
                            {{ user.date_joined }}
                        {% endlanguage %}
                    </div>
                </div>
                <div class="profile-subtitle m-t-40 m-b-5">
                    Hasło:
                </div>
                <div class="profile-variable m-b-20" style="text-align:justify">
                    Hasła nie można sprawdzić, jedyna opcja to zmiana dotychczasowego hasła na nowe. Można to zrobić
                    <a href="{% url 'registration:password_reset' %}" class="m-l-10 m-b-10" style="font-family: Ubuntu-Bold; font-size: 25px; color: #827ffe" onmouseover="this.style.color='black'" onmouseout="this.style.color='#827ffe'">
                                            tutaj</a>
                </div>

                <div class="container-login100-form-btn m-t-50">
                    <a class="user-delete-btn" style="" href="{% url 'main:user_delete' %}">
                        Usuń konto
                    </a>
                </div>
            </div>


        </div>



    </div>
</div>

{% include "main_page/footerbar.html" %}

{% endblock %}

{% block body_scripts_additional %}



{% endblock body_scripts_additional %}